- name: Санҷиши мавҷудияти платформаи Android
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android --project-name chatapp .
          fi

      - name: Танзими minSdk=23 (лозим барои Firebase)
        run: |
          if [ -f android/app/build.gradle.kts ]; then
            sed -i 's/minSdk = flutter.minSdkVersion/minSdk = 23/' android/app/build.gradle.kts
          elif [ -f android/app/build.gradle ]; then
            sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 23/' android/app/build.gradle
          fi
